archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-kind
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/virtuslab/pulumi-kind/provider/v3/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-kind/
release:
  disable: true
changelog:
  skip: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
