// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;
import pl.pawelprazak.pulumi.kind.inputs.*;

@ResourceType(type="kind:index/cluster:Cluster")
public class Cluster extends io.pulumi.resources.CustomResource {
    @OutputExport(name="clientCertificate", type=String.class, parameters={})
    private Output<String> clientCertificate;

    public Output<String> getClientCertificate() {
        return this.clientCertificate;
    }
    @OutputExport(name="clientKey", type=String.class, parameters={})
    private Output<String> clientKey;

    public Output<String> getClientKey() {
        return this.clientKey;
    }
    @OutputExport(name="clusterCaCertificate", type=String.class, parameters={})
    private Output<String> clusterCaCertificate;

    public Output<String> getClusterCaCertificate() {
        return this.clusterCaCertificate;
    }
    @OutputExport(name="endpoint", type=String.class, parameters={})
    private Output<String> endpoint;

    public Output<String> getEndpoint() {
        return this.endpoint;
    }
    @OutputExport(name="kindConfig", type=pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfig.class, parameters={})
    private Output</* @Nullable */ pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfig> kindConfig;

    public Output</* @Nullable */ pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfig> getKindConfig() {
        return this.kindConfig;
    }
    @OutputExport(name="kubeconfig", type=String.class, parameters={})
    private Output<String> kubeconfig;

    public Output<String> getKubeconfig() {
        return this.kubeconfig;
    }
    @OutputExport(name="kubeconfigPath", type=String.class, parameters={})
    private Output<String> kubeconfigPath;

    public Output<String> getKubeconfigPath() {
        return this.kubeconfigPath;
    }
    @OutputExport(name="name", type=String.class, parameters={})
    private Output<String> name;

    public Output<String> getName() {
        return this.name;
    }
    @OutputExport(name="nodeImage", type=String.class, parameters={})
    private Output<String> nodeImage;

    public Output<String> getNodeImage() {
        return this.nodeImage;
    }
    @OutputExport(name="waitForReady", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> waitForReady;

    public Output</* @Nullable */ Boolean> getWaitForReady() {
        return this.waitForReady;
    }

    public Cluster(String name, @Nullable ClusterArgs args, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kind:index/cluster:Cluster", name, args == null ? ClusterArgs.Empty : args, makeResourceOptions(options, Input.empty()));
    }

    private Cluster(String name, Input<String> id, @Nullable ClusterState state, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        super("kind:index/cluster:Cluster", name, state, makeResourceOptions(options, id));
    }

    private static io.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable io.pulumi.resources.CustomResourceOptions options, @Nullable Input<String> id) {
        var defaultOptions = io.pulumi.resources.CustomResourceOptions.builder()
            .setVersion(Utilities.getVersion())
            .build();
        return io.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    public static Cluster get(String name, Input<String> id, @Nullable ClusterState state, @Nullable io.pulumi.resources.CustomResourceOptions options) {
        return new Cluster(name, id, state, options);
    }
}
