// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package kind

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ClusterKindConfig struct {
	ApiVersion              string                       `pulumi:"apiVersion"`
	ContainerdConfigPatches []string                     `pulumi:"containerdConfigPatches"`
	Kind                    string                       `pulumi:"kind"`
	Networking              *ClusterKindConfigNetworking `pulumi:"networking"`
	Nodes                   []ClusterKindConfigNode      `pulumi:"nodes"`
}

// ClusterKindConfigInput is an input type that accepts ClusterKindConfigArgs and ClusterKindConfigOutput values.
// You can construct a concrete instance of `ClusterKindConfigInput` via:
//
//          ClusterKindConfigArgs{...}
type ClusterKindConfigInput interface {
	pulumi.Input

	ToClusterKindConfigOutput() ClusterKindConfigOutput
	ToClusterKindConfigOutputWithContext(context.Context) ClusterKindConfigOutput
}

type ClusterKindConfigArgs struct {
	ApiVersion              pulumi.StringInput                  `pulumi:"apiVersion"`
	ContainerdConfigPatches pulumi.StringArrayInput             `pulumi:"containerdConfigPatches"`
	Kind                    pulumi.StringInput                  `pulumi:"kind"`
	Networking              ClusterKindConfigNetworkingPtrInput `pulumi:"networking"`
	Nodes                   ClusterKindConfigNodeArrayInput     `pulumi:"nodes"`
}

func (ClusterKindConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfig)(nil)).Elem()
}

func (i ClusterKindConfigArgs) ToClusterKindConfigOutput() ClusterKindConfigOutput {
	return i.ToClusterKindConfigOutputWithContext(context.Background())
}

func (i ClusterKindConfigArgs) ToClusterKindConfigOutputWithContext(ctx context.Context) ClusterKindConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigOutput)
}

func (i ClusterKindConfigArgs) ToClusterKindConfigPtrOutput() ClusterKindConfigPtrOutput {
	return i.ToClusterKindConfigPtrOutputWithContext(context.Background())
}

func (i ClusterKindConfigArgs) ToClusterKindConfigPtrOutputWithContext(ctx context.Context) ClusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigOutput).ToClusterKindConfigPtrOutputWithContext(ctx)
}

// ClusterKindConfigPtrInput is an input type that accepts ClusterKindConfigArgs, ClusterKindConfigPtr and ClusterKindConfigPtrOutput values.
// You can construct a concrete instance of `ClusterKindConfigPtrInput` via:
//
//          ClusterKindConfigArgs{...}
//
//  or:
//
//          nil
type ClusterKindConfigPtrInput interface {
	pulumi.Input

	ToClusterKindConfigPtrOutput() ClusterKindConfigPtrOutput
	ToClusterKindConfigPtrOutputWithContext(context.Context) ClusterKindConfigPtrOutput
}

type clusterKindConfigPtrType ClusterKindConfigArgs

func ClusterKindConfigPtr(v *ClusterKindConfigArgs) ClusterKindConfigPtrInput {
	return (*clusterKindConfigPtrType)(v)
}

func (*clusterKindConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterKindConfig)(nil)).Elem()
}

func (i *clusterKindConfigPtrType) ToClusterKindConfigPtrOutput() ClusterKindConfigPtrOutput {
	return i.ToClusterKindConfigPtrOutputWithContext(context.Background())
}

func (i *clusterKindConfigPtrType) ToClusterKindConfigPtrOutputWithContext(ctx context.Context) ClusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigPtrOutput)
}

type ClusterKindConfigOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfig)(nil)).Elem()
}

func (o ClusterKindConfigOutput) ToClusterKindConfigOutput() ClusterKindConfigOutput {
	return o
}

func (o ClusterKindConfigOutput) ToClusterKindConfigOutputWithContext(ctx context.Context) ClusterKindConfigOutput {
	return o
}

func (o ClusterKindConfigOutput) ToClusterKindConfigPtrOutput() ClusterKindConfigPtrOutput {
	return o.ToClusterKindConfigPtrOutputWithContext(context.Background())
}

func (o ClusterKindConfigOutput) ToClusterKindConfigPtrOutputWithContext(ctx context.Context) ClusterKindConfigPtrOutput {
	return o.ApplyT(func(v ClusterKindConfig) *ClusterKindConfig {
		return &v
	}).(ClusterKindConfigPtrOutput)
}
func (o ClusterKindConfigOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v ClusterKindConfig) string { return v.ApiVersion }).(pulumi.StringOutput)
}

func (o ClusterKindConfigOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ClusterKindConfig) []string { return v.ContainerdConfigPatches }).(pulumi.StringArrayOutput)
}

func (o ClusterKindConfigOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v ClusterKindConfig) string { return v.Kind }).(pulumi.StringOutput)
}

func (o ClusterKindConfigOutput) Networking() ClusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v ClusterKindConfig) *ClusterKindConfigNetworking { return v.Networking }).(ClusterKindConfigNetworkingPtrOutput)
}

func (o ClusterKindConfigOutput) Nodes() ClusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v ClusterKindConfig) []ClusterKindConfigNode { return v.Nodes }).(ClusterKindConfigNodeArrayOutput)
}

type ClusterKindConfigPtrOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterKindConfig)(nil)).Elem()
}

func (o ClusterKindConfigPtrOutput) ToClusterKindConfigPtrOutput() ClusterKindConfigPtrOutput {
	return o
}

func (o ClusterKindConfigPtrOutput) ToClusterKindConfigPtrOutputWithContext(ctx context.Context) ClusterKindConfigPtrOutput {
	return o
}

func (o ClusterKindConfigPtrOutput) Elem() ClusterKindConfigOutput {
	return o.ApplyT(func(v *ClusterKindConfig) ClusterKindConfig { return *v }).(ClusterKindConfigOutput)
}

func (o ClusterKindConfigPtrOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.ApiVersion
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigPtrOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ClusterKindConfig) []string {
		if v == nil {
			return nil
		}
		return v.ContainerdConfigPatches
	}).(pulumi.StringArrayOutput)
}

func (o ClusterKindConfigPtrOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.Kind
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigPtrOutput) Networking() ClusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfig) *ClusterKindConfigNetworking {
		if v == nil {
			return nil
		}
		return v.Networking
	}).(ClusterKindConfigNetworkingPtrOutput)
}

func (o ClusterKindConfigPtrOutput) Nodes() ClusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v *ClusterKindConfig) []ClusterKindConfigNode {
		if v == nil {
			return nil
		}
		return v.Nodes
	}).(ClusterKindConfigNodeArrayOutput)
}

type ClusterKindConfigNetworking struct {
	ApiServerAddress  *string `pulumi:"apiServerAddress"`
	ApiServerPort     *int    `pulumi:"apiServerPort"`
	DisableDefaultCni *bool   `pulumi:"disableDefaultCni"`
	IpFamily          *string `pulumi:"ipFamily"`
	KubeProxyMode     *string `pulumi:"kubeProxyMode"`
	PodSubnet         *string `pulumi:"podSubnet"`
	ServiceSubnet     *string `pulumi:"serviceSubnet"`
}

// ClusterKindConfigNetworkingInput is an input type that accepts ClusterKindConfigNetworkingArgs and ClusterKindConfigNetworkingOutput values.
// You can construct a concrete instance of `ClusterKindConfigNetworkingInput` via:
//
//          ClusterKindConfigNetworkingArgs{...}
type ClusterKindConfigNetworkingInput interface {
	pulumi.Input

	ToClusterKindConfigNetworkingOutput() ClusterKindConfigNetworkingOutput
	ToClusterKindConfigNetworkingOutputWithContext(context.Context) ClusterKindConfigNetworkingOutput
}

type ClusterKindConfigNetworkingArgs struct {
	ApiServerAddress  pulumi.StringPtrInput `pulumi:"apiServerAddress"`
	ApiServerPort     pulumi.IntPtrInput    `pulumi:"apiServerPort"`
	DisableDefaultCni pulumi.BoolPtrInput   `pulumi:"disableDefaultCni"`
	IpFamily          pulumi.StringPtrInput `pulumi:"ipFamily"`
	KubeProxyMode     pulumi.StringPtrInput `pulumi:"kubeProxyMode"`
	PodSubnet         pulumi.StringPtrInput `pulumi:"podSubnet"`
	ServiceSubnet     pulumi.StringPtrInput `pulumi:"serviceSubnet"`
}

func (ClusterKindConfigNetworkingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNetworking)(nil)).Elem()
}

func (i ClusterKindConfigNetworkingArgs) ToClusterKindConfigNetworkingOutput() ClusterKindConfigNetworkingOutput {
	return i.ToClusterKindConfigNetworkingOutputWithContext(context.Background())
}

func (i ClusterKindConfigNetworkingArgs) ToClusterKindConfigNetworkingOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNetworkingOutput)
}

func (i ClusterKindConfigNetworkingArgs) ToClusterKindConfigNetworkingPtrOutput() ClusterKindConfigNetworkingPtrOutput {
	return i.ToClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i ClusterKindConfigNetworkingArgs) ToClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNetworkingOutput).ToClusterKindConfigNetworkingPtrOutputWithContext(ctx)
}

// ClusterKindConfigNetworkingPtrInput is an input type that accepts ClusterKindConfigNetworkingArgs, ClusterKindConfigNetworkingPtr and ClusterKindConfigNetworkingPtrOutput values.
// You can construct a concrete instance of `ClusterKindConfigNetworkingPtrInput` via:
//
//          ClusterKindConfigNetworkingArgs{...}
//
//  or:
//
//          nil
type ClusterKindConfigNetworkingPtrInput interface {
	pulumi.Input

	ToClusterKindConfigNetworkingPtrOutput() ClusterKindConfigNetworkingPtrOutput
	ToClusterKindConfigNetworkingPtrOutputWithContext(context.Context) ClusterKindConfigNetworkingPtrOutput
}

type clusterKindConfigNetworkingPtrType ClusterKindConfigNetworkingArgs

func ClusterKindConfigNetworkingPtr(v *ClusterKindConfigNetworkingArgs) ClusterKindConfigNetworkingPtrInput {
	return (*clusterKindConfigNetworkingPtrType)(v)
}

func (*clusterKindConfigNetworkingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterKindConfigNetworking)(nil)).Elem()
}

func (i *clusterKindConfigNetworkingPtrType) ToClusterKindConfigNetworkingPtrOutput() ClusterKindConfigNetworkingPtrOutput {
	return i.ToClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i *clusterKindConfigNetworkingPtrType) ToClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNetworkingPtrOutput)
}

type ClusterKindConfigNetworkingOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNetworkingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNetworking)(nil)).Elem()
}

func (o ClusterKindConfigNetworkingOutput) ToClusterKindConfigNetworkingOutput() ClusterKindConfigNetworkingOutput {
	return o
}

func (o ClusterKindConfigNetworkingOutput) ToClusterKindConfigNetworkingOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingOutput {
	return o
}

func (o ClusterKindConfigNetworkingOutput) ToClusterKindConfigNetworkingPtrOutput() ClusterKindConfigNetworkingPtrOutput {
	return o.ToClusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (o ClusterKindConfigNetworkingOutput) ToClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *ClusterKindConfigNetworking {
		return &v
	}).(ClusterKindConfigNetworkingPtrOutput)
}
func (o ClusterKindConfigNetworkingOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *string { return v.ApiServerAddress }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *int { return v.ApiServerPort }).(pulumi.IntPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *bool { return v.DisableDefaultCni }).(pulumi.BoolPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *string { return v.IpFamily }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *string { return v.KubeProxyMode }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *string { return v.PodSubnet }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNetworking) *string { return v.ServiceSubnet }).(pulumi.StringPtrOutput)
}

type ClusterKindConfigNetworkingPtrOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNetworkingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterKindConfigNetworking)(nil)).Elem()
}

func (o ClusterKindConfigNetworkingPtrOutput) ToClusterKindConfigNetworkingPtrOutput() ClusterKindConfigNetworkingPtrOutput {
	return o
}

func (o ClusterKindConfigNetworkingPtrOutput) ToClusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) ClusterKindConfigNetworkingPtrOutput {
	return o
}

func (o ClusterKindConfigNetworkingPtrOutput) Elem() ClusterKindConfigNetworkingOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) ClusterKindConfigNetworking { return *v }).(ClusterKindConfigNetworkingOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ApiServerAddress
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *int {
		if v == nil {
			return nil
		}
		return v.ApiServerPort
	}).(pulumi.IntPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *bool {
		if v == nil {
			return nil
		}
		return v.DisableDefaultCni
	}).(pulumi.BoolPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.IpFamily
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.KubeProxyMode
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.PodSubnet
	}).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNetworkingPtrOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ServiceSubnet
	}).(pulumi.StringPtrOutput)
}

type ClusterKindConfigNode struct {
	ExtraMounts          []ClusterKindConfigNodeExtraMount       `pulumi:"extraMounts"`
	ExtraPortMappings    []ClusterKindConfigNodeExtraPortMapping `pulumi:"extraPortMappings"`
	Image                *string                                 `pulumi:"image"`
	KubeadmConfigPatches []string                                `pulumi:"kubeadmConfigPatches"`
	Role                 *string                                 `pulumi:"role"`
}

// ClusterKindConfigNodeInput is an input type that accepts ClusterKindConfigNodeArgs and ClusterKindConfigNodeOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeInput` via:
//
//          ClusterKindConfigNodeArgs{...}
type ClusterKindConfigNodeInput interface {
	pulumi.Input

	ToClusterKindConfigNodeOutput() ClusterKindConfigNodeOutput
	ToClusterKindConfigNodeOutputWithContext(context.Context) ClusterKindConfigNodeOutput
}

type ClusterKindConfigNodeArgs struct {
	ExtraMounts          ClusterKindConfigNodeExtraMountArrayInput       `pulumi:"extraMounts"`
	ExtraPortMappings    ClusterKindConfigNodeExtraPortMappingArrayInput `pulumi:"extraPortMappings"`
	Image                pulumi.StringPtrInput                           `pulumi:"image"`
	KubeadmConfigPatches pulumi.StringArrayInput                         `pulumi:"kubeadmConfigPatches"`
	Role                 pulumi.StringPtrInput                           `pulumi:"role"`
}

func (ClusterKindConfigNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNode)(nil)).Elem()
}

func (i ClusterKindConfigNodeArgs) ToClusterKindConfigNodeOutput() ClusterKindConfigNodeOutput {
	return i.ToClusterKindConfigNodeOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeArgs) ToClusterKindConfigNodeOutputWithContext(ctx context.Context) ClusterKindConfigNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeOutput)
}

// ClusterKindConfigNodeArrayInput is an input type that accepts ClusterKindConfigNodeArray and ClusterKindConfigNodeArrayOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeArrayInput` via:
//
//          ClusterKindConfigNodeArray{ ClusterKindConfigNodeArgs{...} }
type ClusterKindConfigNodeArrayInput interface {
	pulumi.Input

	ToClusterKindConfigNodeArrayOutput() ClusterKindConfigNodeArrayOutput
	ToClusterKindConfigNodeArrayOutputWithContext(context.Context) ClusterKindConfigNodeArrayOutput
}

type ClusterKindConfigNodeArray []ClusterKindConfigNodeInput

func (ClusterKindConfigNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNode)(nil)).Elem()
}

func (i ClusterKindConfigNodeArray) ToClusterKindConfigNodeArrayOutput() ClusterKindConfigNodeArrayOutput {
	return i.ToClusterKindConfigNodeArrayOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeArray) ToClusterKindConfigNodeArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeArrayOutput)
}

type ClusterKindConfigNodeOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNode)(nil)).Elem()
}

func (o ClusterKindConfigNodeOutput) ToClusterKindConfigNodeOutput() ClusterKindConfigNodeOutput {
	return o
}

func (o ClusterKindConfigNodeOutput) ToClusterKindConfigNodeOutputWithContext(ctx context.Context) ClusterKindConfigNodeOutput {
	return o
}

func (o ClusterKindConfigNodeOutput) ExtraMounts() ClusterKindConfigNodeExtraMountArrayOutput {
	return o.ApplyT(func(v ClusterKindConfigNode) []ClusterKindConfigNodeExtraMount { return v.ExtraMounts }).(ClusterKindConfigNodeExtraMountArrayOutput)
}

func (o ClusterKindConfigNodeOutput) ExtraPortMappings() ClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o.ApplyT(func(v ClusterKindConfigNode) []ClusterKindConfigNodeExtraPortMapping { return v.ExtraPortMappings }).(ClusterKindConfigNodeExtraPortMappingArrayOutput)
}

func (o ClusterKindConfigNodeOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNode) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNodeOutput) KubeadmConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ClusterKindConfigNode) []string { return v.KubeadmConfigPatches }).(pulumi.StringArrayOutput)
}

func (o ClusterKindConfigNodeOutput) Role() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNode) *string { return v.Role }).(pulumi.StringPtrOutput)
}

type ClusterKindConfigNodeArrayOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNode)(nil)).Elem()
}

func (o ClusterKindConfigNodeArrayOutput) ToClusterKindConfigNodeArrayOutput() ClusterKindConfigNodeArrayOutput {
	return o
}

func (o ClusterKindConfigNodeArrayOutput) ToClusterKindConfigNodeArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeArrayOutput {
	return o
}

func (o ClusterKindConfigNodeArrayOutput) Index(i pulumi.IntInput) ClusterKindConfigNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ClusterKindConfigNode {
		return vs[0].([]ClusterKindConfigNode)[vs[1].(int)]
	}).(ClusterKindConfigNodeOutput)
}

type ClusterKindConfigNodeExtraMount struct {
	ContainerPath *string `pulumi:"containerPath"`
	HostPath      *string `pulumi:"hostPath"`
}

// ClusterKindConfigNodeExtraMountInput is an input type that accepts ClusterKindConfigNodeExtraMountArgs and ClusterKindConfigNodeExtraMountOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeExtraMountInput` via:
//
//          ClusterKindConfigNodeExtraMountArgs{...}
type ClusterKindConfigNodeExtraMountInput interface {
	pulumi.Input

	ToClusterKindConfigNodeExtraMountOutput() ClusterKindConfigNodeExtraMountOutput
	ToClusterKindConfigNodeExtraMountOutputWithContext(context.Context) ClusterKindConfigNodeExtraMountOutput
}

type ClusterKindConfigNodeExtraMountArgs struct {
	ContainerPath pulumi.StringPtrInput `pulumi:"containerPath"`
	HostPath      pulumi.StringPtrInput `pulumi:"hostPath"`
}

func (ClusterKindConfigNodeExtraMountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i ClusterKindConfigNodeExtraMountArgs) ToClusterKindConfigNodeExtraMountOutput() ClusterKindConfigNodeExtraMountOutput {
	return i.ToClusterKindConfigNodeExtraMountOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeExtraMountArgs) ToClusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraMountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeExtraMountOutput)
}

// ClusterKindConfigNodeExtraMountArrayInput is an input type that accepts ClusterKindConfigNodeExtraMountArray and ClusterKindConfigNodeExtraMountArrayOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeExtraMountArrayInput` via:
//
//          ClusterKindConfigNodeExtraMountArray{ ClusterKindConfigNodeExtraMountArgs{...} }
type ClusterKindConfigNodeExtraMountArrayInput interface {
	pulumi.Input

	ToClusterKindConfigNodeExtraMountArrayOutput() ClusterKindConfigNodeExtraMountArrayOutput
	ToClusterKindConfigNodeExtraMountArrayOutputWithContext(context.Context) ClusterKindConfigNodeExtraMountArrayOutput
}

type ClusterKindConfigNodeExtraMountArray []ClusterKindConfigNodeExtraMountInput

func (ClusterKindConfigNodeExtraMountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i ClusterKindConfigNodeExtraMountArray) ToClusterKindConfigNodeExtraMountArrayOutput() ClusterKindConfigNodeExtraMountArrayOutput {
	return i.ToClusterKindConfigNodeExtraMountArrayOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeExtraMountArray) ToClusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraMountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeExtraMountArrayOutput)
}

type ClusterKindConfigNodeExtraMountOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeExtraMountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o ClusterKindConfigNodeExtraMountOutput) ToClusterKindConfigNodeExtraMountOutput() ClusterKindConfigNodeExtraMountOutput {
	return o
}

func (o ClusterKindConfigNodeExtraMountOutput) ToClusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraMountOutput {
	return o
}

func (o ClusterKindConfigNodeExtraMountOutput) ContainerPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraMount) *string { return v.ContainerPath }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNodeExtraMountOutput) HostPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraMount) *string { return v.HostPath }).(pulumi.StringPtrOutput)
}

type ClusterKindConfigNodeExtraMountArrayOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeExtraMountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o ClusterKindConfigNodeExtraMountArrayOutput) ToClusterKindConfigNodeExtraMountArrayOutput() ClusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o ClusterKindConfigNodeExtraMountArrayOutput) ToClusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o ClusterKindConfigNodeExtraMountArrayOutput) Index(i pulumi.IntInput) ClusterKindConfigNodeExtraMountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ClusterKindConfigNodeExtraMount {
		return vs[0].([]ClusterKindConfigNodeExtraMount)[vs[1].(int)]
	}).(ClusterKindConfigNodeExtraMountOutput)
}

type ClusterKindConfigNodeExtraPortMapping struct {
	ContainerPort *int    `pulumi:"containerPort"`
	HostPort      *int    `pulumi:"hostPort"`
	ListenAddress *string `pulumi:"listenAddress"`
	Protocol      *string `pulumi:"protocol"`
}

// ClusterKindConfigNodeExtraPortMappingInput is an input type that accepts ClusterKindConfigNodeExtraPortMappingArgs and ClusterKindConfigNodeExtraPortMappingOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeExtraPortMappingInput` via:
//
//          ClusterKindConfigNodeExtraPortMappingArgs{...}
type ClusterKindConfigNodeExtraPortMappingInput interface {
	pulumi.Input

	ToClusterKindConfigNodeExtraPortMappingOutput() ClusterKindConfigNodeExtraPortMappingOutput
	ToClusterKindConfigNodeExtraPortMappingOutputWithContext(context.Context) ClusterKindConfigNodeExtraPortMappingOutput
}

type ClusterKindConfigNodeExtraPortMappingArgs struct {
	ContainerPort pulumi.IntPtrInput    `pulumi:"containerPort"`
	HostPort      pulumi.IntPtrInput    `pulumi:"hostPort"`
	ListenAddress pulumi.StringPtrInput `pulumi:"listenAddress"`
	Protocol      pulumi.StringPtrInput `pulumi:"protocol"`
}

func (ClusterKindConfigNodeExtraPortMappingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i ClusterKindConfigNodeExtraPortMappingArgs) ToClusterKindConfigNodeExtraPortMappingOutput() ClusterKindConfigNodeExtraPortMappingOutput {
	return i.ToClusterKindConfigNodeExtraPortMappingOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeExtraPortMappingArgs) ToClusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeExtraPortMappingOutput)
}

// ClusterKindConfigNodeExtraPortMappingArrayInput is an input type that accepts ClusterKindConfigNodeExtraPortMappingArray and ClusterKindConfigNodeExtraPortMappingArrayOutput values.
// You can construct a concrete instance of `ClusterKindConfigNodeExtraPortMappingArrayInput` via:
//
//          ClusterKindConfigNodeExtraPortMappingArray{ ClusterKindConfigNodeExtraPortMappingArgs{...} }
type ClusterKindConfigNodeExtraPortMappingArrayInput interface {
	pulumi.Input

	ToClusterKindConfigNodeExtraPortMappingArrayOutput() ClusterKindConfigNodeExtraPortMappingArrayOutput
	ToClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Context) ClusterKindConfigNodeExtraPortMappingArrayOutput
}

type ClusterKindConfigNodeExtraPortMappingArray []ClusterKindConfigNodeExtraPortMappingInput

func (ClusterKindConfigNodeExtraPortMappingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i ClusterKindConfigNodeExtraPortMappingArray) ToClusterKindConfigNodeExtraPortMappingArrayOutput() ClusterKindConfigNodeExtraPortMappingArrayOutput {
	return i.ToClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Background())
}

func (i ClusterKindConfigNodeExtraPortMappingArray) ToClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraPortMappingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterKindConfigNodeExtraPortMappingArrayOutput)
}

type ClusterKindConfigNodeExtraPortMappingOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeExtraPortMappingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) ToClusterKindConfigNodeExtraPortMappingOutput() ClusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) ToClusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) ContainerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraPortMapping) *int { return v.ContainerPort }).(pulumi.IntPtrOutput)
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) HostPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraPortMapping) *int { return v.HostPort }).(pulumi.IntPtrOutput)
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) ListenAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraPortMapping) *string { return v.ListenAddress }).(pulumi.StringPtrOutput)
}

func (o ClusterKindConfigNodeExtraPortMappingOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterKindConfigNodeExtraPortMapping) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

type ClusterKindConfigNodeExtraPortMappingArrayOutput struct{ *pulumi.OutputState }

func (ClusterKindConfigNodeExtraPortMappingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ClusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o ClusterKindConfigNodeExtraPortMappingArrayOutput) ToClusterKindConfigNodeExtraPortMappingArrayOutput() ClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o ClusterKindConfigNodeExtraPortMappingArrayOutput) ToClusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) ClusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o ClusterKindConfigNodeExtraPortMappingArrayOutput) Index(i pulumi.IntInput) ClusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ClusterKindConfigNodeExtraPortMapping {
		return vs[0].([]ClusterKindConfigNodeExtraPortMapping)[vs[1].(int)]
	}).(ClusterKindConfigNodeExtraPortMappingOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterKindConfigOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigPtrOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNetworkingOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNetworkingPtrOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeArrayOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeExtraMountOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeExtraMountArrayOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeExtraPortMappingOutput{})
	pulumi.RegisterOutputType(ClusterKindConfigNodeExtraPortMappingArrayOutput{})
}
