// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind.Outputs
{

    [OutputType]
    public sealed class ClusterKindConfigNodeExtraPortMapping
    {
        public readonly int? ContainerPort;
        public readonly int? HostPort;
        public readonly string? ListenAddress;
        public readonly string? Protocol;

        [OutputConstructor]
        private ClusterKindConfigNodeExtraPortMapping(
            int? containerPort,

            int? hostPort,

            string? listenAddress,

            string? protocol)
        {
            ContainerPort = containerPort;
            HostPort = hostPort;
            ListenAddress = listenAddress;
            Protocol = protocol;
        }
    }
}
