// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind.Outputs
{

    [OutputType]
    public sealed class ClusterKindConfigNetworking
    {
        public readonly string? ApiServerAddress;
        public readonly int? ApiServerPort;
        public readonly bool? DisableDefaultCni;
        public readonly string? IpFamily;
        public readonly string? KubeProxyMode;
        public readonly string? PodSubnet;
        public readonly string? ServiceSubnet;

        [OutputConstructor]
        private ClusterKindConfigNetworking(
            string? apiServerAddress,

            int? apiServerPort,

            bool? disableDefaultCni,

            string? ipFamily,

            string? kubeProxyMode,

            string? podSubnet,

            string? serviceSubnet)
        {
            ApiServerAddress = apiServerAddress;
            ApiServerPort = apiServerPort;
            DisableDefaultCni = disableDefaultCni;
            IpFamily = ipFamily;
            KubeProxyMode = kubeProxyMode;
            PodSubnet = podSubnet;
            ServiceSubnet = serviceSubnet;
        }
    }
}
