// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;


public final class ClusterKindConfigNodeExtraMountArgs extends io.pulumi.resources.ResourceArgs {

    public static final ClusterKindConfigNodeExtraMountArgs Empty = new ClusterKindConfigNodeExtraMountArgs();

    @InputImport(name="containerPath")
    private final @Nullable Input<String> containerPath;

    public Input<String> getContainerPath() {
        return this.containerPath == null ? Input.empty() : this.containerPath;
    }

    @InputImport(name="hostPath")
    private final @Nullable Input<String> hostPath;

    public Input<String> getHostPath() {
        return this.hostPath == null ? Input.empty() : this.hostPath;
    }

    public ClusterKindConfigNodeExtraMountArgs(
        @Nullable Input<String> containerPath,
        @Nullable Input<String> hostPath) {
        this.containerPath = containerPath;
        this.hostPath = hostPath;
    }

    private ClusterKindConfigNodeExtraMountArgs() {
        this.containerPath = Input.empty();
        this.hostPath = Input.empty();
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterKindConfigNodeExtraMountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<String> containerPath;
        private @Nullable Input<String> hostPath;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterKindConfigNodeExtraMountArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.containerPath = defaults.containerPath;
    	      this.hostPath = defaults.hostPath;
        }

        public Builder setContainerPath(@Nullable Input<String> containerPath) {
            this.containerPath = containerPath;
            return this;
        }

        public Builder setContainerPath(@Nullable String containerPath) {
            this.containerPath = Input.ofNullable(containerPath);
            return this;
        }

        public Builder setHostPath(@Nullable Input<String> hostPath) {
            this.hostPath = hostPath;
            return this;
        }

        public Builder setHostPath(@Nullable String hostPath) {
            this.hostPath = Input.ofNullable(hostPath);
            return this;
        }

        public ClusterKindConfigNodeExtraMountArgs build() {
            return new ClusterKindConfigNodeExtraMountArgs(containerPath, hostPath);
        }
    }
}
