// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;


public final class ClusterKindConfigArgs extends io.pulumi.resources.ResourceArgs {

    public static final ClusterKindConfigArgs Empty = ClusterKindConfigArgs.builder().build();

    @InputImport(name="apiVersion", required=true)
    private final Input<String> apiVersion;

    public Input<String> getApiVersion() {
        return this.apiVersion;
    }

    @InputImport(name="containerdConfigPatches")
    private final @Nullable Input<List<String>> containerdConfigPatches;

    public Input<List<String>> getContainerdConfigPatches() {
        return Input.ofNullable(this.containerdConfigPatches);
    }

    @InputImport(name="kind", required=true)
    private final Input<String> kind;

    public Input<String> getKind() {
        return this.kind;
    }

    @InputImport(name="networking")
    private final @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs> networking;

    public Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs> getNetworking() {
        return Input.ofNullable(this.networking);
    }

    @InputImport(name="nodes")
    private final @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs>> nodes;

    public Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs>> getNodes() {
        return Input.ofNullable(this.nodes);
    }

    public ClusterKindConfigArgs(
        Input<String> apiVersion,
        @Nullable Input<List<String>> containerdConfigPatches,
        Input<String> kind,
        @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs> networking,
        @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs>> nodes) {
        this.apiVersion = Objects.requireNonNull(apiVersion);
        this.containerdConfigPatches = containerdConfigPatches;
        this.kind = Objects.requireNonNull(kind);
        this.networking = networking;
        this.nodes = nodes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterKindConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Input<String> apiVersion;
        private @Nullable Input<List<String>> containerdConfigPatches;
        private Input<String> kind;
        private @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs> networking;
        private @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs>> nodes;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterKindConfigArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiVersion = defaults.apiVersion;
    	      this.containerdConfigPatches = defaults.containerdConfigPatches;
    	      this.kind = defaults.kind;
    	      this.networking = defaults.networking;
    	      this.nodes = defaults.nodes;
        }

        public Builder setApiVersion(Input<String> apiVersion) {
            this.apiVersion = Objects.requireNonNull(apiVersion);
            return this;
        }

        public Builder setApiVersion(String apiVersion) {
            this.apiVersion = Input.of(Objects.requireNonNull(apiVersion));
            return this;
        }

        public Builder setContainerdConfigPatches(@Nullable Input<List<String>> containerdConfigPatches) {
            this.containerdConfigPatches = containerdConfigPatches;
            return this;
        }

        public Builder setContainerdConfigPatches(@Nullable List<String> containerdConfigPatches) {
            this.containerdConfigPatches = Input.ofNullable(containerdConfigPatches);
            return this;
        }

        public Builder setKind(Input<String> kind) {
            this.kind = Objects.requireNonNull(kind);
            return this;
        }

        public Builder setKind(String kind) {
            this.kind = Input.of(Objects.requireNonNull(kind));
            return this;
        }

        public Builder setNetworking(@Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs> networking) {
            this.networking = networking;
            return this;
        }

        public Builder setNetworking(@Nullable pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNetworkingArgs networking) {
            this.networking = Input.ofNullable(networking);
            return this;
        }

        public Builder setNodes(@Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs>> nodes) {
            this.nodes = nodes;
            return this;
        }

        public Builder setNodes(@Nullable List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeArgs> nodes) {
            this.nodes = Input.ofNullable(nodes);
            return this;
        }

        public ClusterKindConfigArgs build() {
            return new ClusterKindConfigArgs(apiVersion, containerdConfigPatches, kind, networking, nodes);
        }
    }
}
