// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;


public final class ClusterKindConfigNodeGetArgs extends io.pulumi.resources.ResourceArgs {

    public static final ClusterKindConfigNodeGetArgs Empty = ClusterKindConfigNodeGetArgs.builder().build();

    @InputImport(name="extraMounts")
    private final @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs>> extraMounts;

    public Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs>> getExtraMounts() {
        return Input.ofNullable(this.extraMounts);
    }

    @InputImport(name="extraPortMappings")
    private final @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs>> extraPortMappings;

    public Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs>> getExtraPortMappings() {
        return Input.ofNullable(this.extraPortMappings);
    }

    @InputImport(name="image")
    private final @Nullable Input<String> image;

    public Input<String> getImage() {
        return Input.ofNullable(this.image);
    }

    @InputImport(name="kubeadmConfigPatches")
    private final @Nullable Input<List<String>> kubeadmConfigPatches;

    public Input<List<String>> getKubeadmConfigPatches() {
        return Input.ofNullable(this.kubeadmConfigPatches);
    }

    @InputImport(name="role")
    private final @Nullable Input<String> role;

    public Input<String> getRole() {
        return Input.ofNullable(this.role);
    }

    public ClusterKindConfigNodeGetArgs(
        @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs>> extraMounts,
        @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs>> extraPortMappings,
        @Nullable Input<String> image,
        @Nullable Input<List<String>> kubeadmConfigPatches,
        @Nullable Input<String> role) {
        this.extraMounts = extraMounts;
        this.extraPortMappings = extraPortMappings;
        this.image = image;
        this.kubeadmConfigPatches = kubeadmConfigPatches;
        this.role = role;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterKindConfigNodeGetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs>> extraMounts;
        private @Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs>> extraPortMappings;
        private @Nullable Input<String> image;
        private @Nullable Input<List<String>> kubeadmConfigPatches;
        private @Nullable Input<String> role;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterKindConfigNodeGetArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.extraMounts = defaults.extraMounts;
    	      this.extraPortMappings = defaults.extraPortMappings;
    	      this.image = defaults.image;
    	      this.kubeadmConfigPatches = defaults.kubeadmConfigPatches;
    	      this.role = defaults.role;
        }

        public Builder setExtraMounts(@Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs>> extraMounts) {
            this.extraMounts = extraMounts;
            return this;
        }

        public Builder setExtraMounts(@Nullable List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraMountGetArgs> extraMounts) {
            this.extraMounts = Input.ofNullable(extraMounts);
            return this;
        }

        public Builder setExtraPortMappings(@Nullable Input<List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs>> extraPortMappings) {
            this.extraPortMappings = extraPortMappings;
            return this;
        }

        public Builder setExtraPortMappings(@Nullable List<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigNodeExtraPortMappingGetArgs> extraPortMappings) {
            this.extraPortMappings = Input.ofNullable(extraPortMappings);
            return this;
        }

        public Builder setImage(@Nullable Input<String> image) {
            this.image = image;
            return this;
        }

        public Builder setImage(@Nullable String image) {
            this.image = Input.ofNullable(image);
            return this;
        }

        public Builder setKubeadmConfigPatches(@Nullable Input<List<String>> kubeadmConfigPatches) {
            this.kubeadmConfigPatches = kubeadmConfigPatches;
            return this;
        }

        public Builder setKubeadmConfigPatches(@Nullable List<String> kubeadmConfigPatches) {
            this.kubeadmConfigPatches = Input.ofNullable(kubeadmConfigPatches);
            return this;
        }

        public Builder setRole(@Nullable Input<String> role) {
            this.role = role;
            return this;
        }

        public Builder setRole(@Nullable String role) {
            this.role = Input.ofNullable(role);
            return this;
        }

        public ClusterKindConfigNodeGetArgs build() {
            return new ClusterKindConfigNodeGetArgs(extraMounts, extraPortMappings, image, kubeadmConfigPatches, role);
        }
    }
}
