// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.inputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;


public final class ClusterArgs extends io.pulumi.resources.ResourceArgs {

    public static final ClusterArgs Empty = ClusterArgs.builder().build();

    @InputImport(name="kindConfig")
    private final @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs> kindConfig;

    public Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs> getKindConfig() {
        return Input.ofNullable(this.kindConfig);
    }

    @InputImport(name="kubeconfigPath")
    private final @Nullable Input<String> kubeconfigPath;

    public Input<String> getKubeconfigPath() {
        return Input.ofNullable(this.kubeconfigPath);
    }

    @InputImport(name="name")
    private final @Nullable Input<String> name;

    public Input<String> getName() {
        return Input.ofNullable(this.name);
    }

    @InputImport(name="nodeImage")
    private final @Nullable Input<String> nodeImage;

    public Input<String> getNodeImage() {
        return Input.ofNullable(this.nodeImage);
    }

    @InputImport(name="waitForReady")
    private final @Nullable Input<Boolean> waitForReady;

    public Input<Boolean> getWaitForReady() {
        return Input.ofNullable(this.waitForReady);
    }

    public ClusterArgs(
        @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs> kindConfig,
        @Nullable Input<String> kubeconfigPath,
        @Nullable Input<String> name,
        @Nullable Input<String> nodeImage,
        @Nullable Input<Boolean> waitForReady) {
        this.kindConfig = kindConfig;
        this.kubeconfigPath = kubeconfigPath;
        this.name = name;
        this.nodeImage = nodeImage;
        this.waitForReady = waitForReady;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs> kindConfig;
        private @Nullable Input<String> kubeconfigPath;
        private @Nullable Input<String> name;
        private @Nullable Input<String> nodeImage;
        private @Nullable Input<Boolean> waitForReady;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.kindConfig = defaults.kindConfig;
    	      this.kubeconfigPath = defaults.kubeconfigPath;
    	      this.name = defaults.name;
    	      this.nodeImage = defaults.nodeImage;
    	      this.waitForReady = defaults.waitForReady;
        }

        public Builder setKindConfig(@Nullable Input<pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs> kindConfig) {
            this.kindConfig = kindConfig;
            return this;
        }

        public Builder setKindConfig(@Nullable pl.pawelprazak.pulumi.kind.inputs.ClusterKindConfigArgs kindConfig) {
            this.kindConfig = Input.ofNullable(kindConfig);
            return this;
        }

        public Builder setKubeconfigPath(@Nullable Input<String> kubeconfigPath) {
            this.kubeconfigPath = kubeconfigPath;
            return this;
        }

        public Builder setKubeconfigPath(@Nullable String kubeconfigPath) {
            this.kubeconfigPath = Input.ofNullable(kubeconfigPath);
            return this;
        }

        public Builder setName(@Nullable Input<String> name) {
            this.name = name;
            return this;
        }

        public Builder setName(@Nullable String name) {
            this.name = Input.ofNullable(name);
            return this;
        }

        public Builder setNodeImage(@Nullable Input<String> nodeImage) {
            this.nodeImage = nodeImage;
            return this;
        }

        public Builder setNodeImage(@Nullable String nodeImage) {
            this.nodeImage = Input.ofNullable(nodeImage);
            return this;
        }

        public Builder setWaitForReady(@Nullable Input<Boolean> waitForReady) {
            this.waitForReady = waitForReady;
            return this;
        }

        public Builder setWaitForReady(@Nullable Boolean waitForReady) {
            this.waitForReady = Input.ofNullable(waitForReady);
            return this;
        }

        public ClusterArgs build() {
            return new ClusterArgs(kindConfig, kubeconfigPath, name, nodeImage, waitForReady);
        }
    }
}
