// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ClusterKindConfig {
    apiVersion: string;
    containerdConfigPatches?: string[];
    kind: string;
    networking?: outputs.ClusterKindConfigNetworking;
    nodes?: outputs.ClusterKindConfigNode[];
}

export interface ClusterKindConfigNetworking {
    apiServerAddress?: string;
    apiServerPort?: number;
    disableDefaultCni?: boolean;
    ipFamily?: string;
    kubeProxyMode?: string;
    podSubnet?: string;
    serviceSubnet?: string;
}

export interface ClusterKindConfigNode {
    extraMounts?: outputs.ClusterKindConfigNodeExtraMount[];
    extraPortMappings?: outputs.ClusterKindConfigNodeExtraPortMapping[];
    image?: string;
    kubeadmConfigPatches?: string[];
    role?: string;
}

export interface ClusterKindConfigNodeExtraMount {
    containerPath?: string;
    hostPath?: string;
}

export interface ClusterKindConfigNodeExtraPortMapping {
    containerPort?: number;
    hostPort?: number;
    listenAddress?: string;
    protocol?: string;
}
