// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;

@OutputCustomType
public final class ClusterKindConfigNode {
    private final @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraMount> extraMounts;
    private final @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraPortMapping> extraPortMappings;
    private final @Nullable String image;
    private final @Nullable List<String> kubeadmConfigPatches;
    private final @Nullable String role;

    @OutputCustomType.Constructor({"extraMounts","extraPortMappings","image","kubeadmConfigPatches","role"})
    private ClusterKindConfigNode(
        @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraMount> extraMounts,
        @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraPortMapping> extraPortMappings,
        @Nullable String image,
        @Nullable List<String> kubeadmConfigPatches,
        @Nullable String role) {
        this.extraMounts = extraMounts;
        this.extraPortMappings = extraPortMappings;
        this.image = image;
        this.kubeadmConfigPatches = kubeadmConfigPatches;
        this.role = role;
    }

    public List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraMount> getExtraMounts() {
        return this.extraMounts == null ? List.of() : this.extraMounts;
    }
    public List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraPortMapping> getExtraPortMappings() {
        return this.extraPortMappings == null ? List.of() : this.extraPortMappings;
    }
    public Optional<String> getImage() {
        return Optional.ofNullable(this.image);
    }
    public List<String> getKubeadmConfigPatches() {
        return this.kubeadmConfigPatches == null ? List.of() : this.kubeadmConfigPatches;
    }
    public Optional<String> getRole() {
        return Optional.ofNullable(this.role);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterKindConfigNode defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraMount> extraMounts;
        private @Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraPortMapping> extraPortMappings;
        private @Nullable String image;
        private @Nullable List<String> kubeadmConfigPatches;
        private @Nullable String role;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterKindConfigNode defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.extraMounts = defaults.extraMounts;
    	      this.extraPortMappings = defaults.extraPortMappings;
    	      this.image = defaults.image;
    	      this.kubeadmConfigPatches = defaults.kubeadmConfigPatches;
    	      this.role = defaults.role;
        }

        public Builder setExtraMounts(@Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraMount> extraMounts) {
            this.extraMounts = extraMounts;
            return this;
        }

        public Builder setExtraPortMappings(@Nullable List<pl.pawelprazak.pulumi.kind.outputs.ClusterKindConfigNodeExtraPortMapping> extraPortMappings) {
            this.extraPortMappings = extraPortMappings;
            return this;
        }

        public Builder setImage(@Nullable String image) {
            this.image = image;
            return this;
        }

        public Builder setKubeadmConfigPatches(@Nullable List<String> kubeadmConfigPatches) {
            this.kubeadmConfigPatches = kubeadmConfigPatches;
            return this;
        }

        public Builder setRole(@Nullable String role) {
            this.role = role;
            return this;
        }

        public ClusterKindConfigNode build() {
            return new ClusterKindConfigNode(extraMounts, extraPortMappings, image, kubeadmConfigPatches, role);
        }
    }
}
