// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package pl.pawelprazak.pulumi.kind.outputs;

import javax.annotation.Nullable;
import java.util.Objects;
import java.util.Optional;
import java.util.Map;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import io.pulumi.core.*;
import io.pulumi.core.internal.annotations.*;
import pl.pawelprazak.pulumi.kind.Utilities;

@OutputCustomType
public final class ClusterKindConfigNodeExtraMount {
    private final @Nullable String containerPath;
    private final @Nullable String hostPath;

    @OutputCustomType.Constructor({"containerPath","hostPath"})
    private ClusterKindConfigNodeExtraMount(
        @Nullable String containerPath,
        @Nullable String hostPath) {
        this.containerPath = containerPath;
        this.hostPath = hostPath;
    }

    public Optional<String> getContainerPath() {
        return Optional.ofNullable(this.containerPath);
    }
    public Optional<String> getHostPath() {
        return Optional.ofNullable(this.hostPath);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterKindConfigNodeExtraMount defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String containerPath;
        private @Nullable String hostPath;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterKindConfigNodeExtraMount defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.containerPath = defaults.containerPath;
    	      this.hostPath = defaults.hostPath;
        }

        public Builder setContainerPath(@Nullable String containerPath) {
            this.containerPath = containerPath;
            return this;
        }

        public Builder setHostPath(@Nullable String hostPath) {
            this.hostPath = hostPath;
            return this;
        }

        public ClusterKindConfigNodeExtraMount build() {
            return new ClusterKindConfigNodeExtraMount(containerPath, hostPath);
        }
    }
}
